name: Deploy Ghost infrastructure 
on: [workflow_dispatch]

env:
  RESOURCE_GROUP_NAME: ghost-rg-we

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az group create -n $RESOURCE_GROUP_NAME -l 'West Europe'

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        template: ./infra-as-code/main.bicep
        parameters: administratorLoginPassword=${{ secrets.AZURE_MYSQL_PASSWORD }}
        failOnStdErr: false
